---
  title: "RData Anlysis Project"
author: "Cassidie Kassidy and Maddie"
date: "Nov 2021"
output:
  html_document:
  theme: cerulean
highlight: pygments
toc: true
toc_float:
  collapsed: true
smooth_scroll: false
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidycensus)
library(janitor)
library(lubridate)
library(sf)
library(tigris)
install.packages("usmap")
library(usmap)

```

```{r}
install.packages("censusxy")
library(censusxy)
```

```{r}
Shootings<-read_csv("data-police-shootings-master/fatal-police-shootings-data.csv")

census_api_key("0105753aba54d204fb6c33c44044ae59449b3773", overwrite =TRUE)
```
###Question 1:
Are Police shootings primarily only happening in majority Black neighborhoods even when the victim is not black?
```{r}
shootings<-read_csv("data/fatal-police-shootings-data.csv")%>%
    filter(!is.na(longitude)) 

shootings_geocoded <- tibble()


for (row_number in 1:nrow(shootings_geocoded)) {

  #making one row dataframe with shooting data geocoded
  row_df <- shootings %>%
    slice(row_number)
  #extract value for each object latitude and longitude
  longitude <- row_df$longitude
  latitude <- row_df$latitude
  #get census tract for row
  census_results <- cxy_geography(longitude, latitude) %>%
    select(Census.Tracts.GEOID) %>%
    clean_names()
#add census tract to dataframe 
   row_df <- row_df %>%
     bind_cols(census_results) 
   
  shootings_geocoded <- shootings_geocoded %>%
    bind_rows(row_df) 
}
```
```{r}
#read in the data
data1 <- read_rds("data/geocoded_results_500.rds")
data2 <- read_rds("data/geocoded_results_1000.rds")
data3 <- read_rds("data/geocoded_results_1500.rds")
data4 <- read_rds("data/geocoded_results_2000.rds")
data5 <- read_rds("data/geocoded_results_2500.rds")
data6 <- read_rds("data/geocoded_results_3000.rds")
data7 <- read_rds("data/geocoded_results_3500.rds")
data8 <- read_rds("data/geocoded_results_4000.rds")
data9 <- read_rds("data/geocoded_results_4500.rds")

```
###Question 2:
Do these shootings mostly occur in low income areas?
```{r}

```

###Question 3:
Are police shootings still happening disproportionately affecting black people regardless of the area (even in white neighborhoods)?

```{r}

```

